lib: [
  "_build/install/default/lib/testify_runtime/META"
  "_build/install/default/lib/testify_runtime/dune-package"
  "_build/install/default/lib/testify_runtime/opam"
  "_build/install/default/lib/testify_runtime/testify_runtime.a"
  "_build/install/default/lib/testify_runtime/testify_runtime.cma"
  "_build/install/default/lib/testify_runtime/testify_runtime.cmi"
  "_build/install/default/lib/testify_runtime/testify_runtime.cmt"
  "_build/install/default/lib/testify_runtime/testify_runtime.cmx"
  "_build/install/default/lib/testify_runtime/testify_runtime.cmxa"
  "_build/install/default/lib/testify_runtime/testify_runtime.ml"
]
libexec: [
  "_build/install/default/lib/testify_runtime/testify_runtime.cmxs"
]
doc: [
  "_build/install/default/doc/testify_runtime/README.md"
]
